[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/themes"]
    type = "archive"
    url = "https://github.com/dracula/zsh/archive/master.tar.gz"
    stripComponents = 1

[".nvm"]
    type = "archive"
    url = "https://github.com/nvm-sh/nvm/archive/refs/tags/v0.39.2.tar.gz"
    exact = true
    stripComponents = 1
